version: '3'

services:
  web:
    image: node:14
    container_name: web-app
    environment:
      - PGHOST=db
      - PGDATABASE=todo_db
      - PGUSER=postgres
    ports:
      - "4000:4000"
    volumes:
      - ./src:/app
    working_dir: /app
    command: "node -r dotenv/config src/index.js"
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=todo_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
